import Head from "next/head";
import "../styles/globals.css";
import { Footer, Navbar } from "../utils/AppComponents";

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Component {...pageProps} />
			<Footer />
		</>
	);
}

export default MyApp;
