import Head from "next/head";

const Home = () => {
	return (
		<>
			<Head>
				<title>Home | DarkLordDev</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="container mx-auto">
				<h1 className="text-3xl font-bold">Hello World!</h1>
			</div>
		</>
	);
};

export default Home;
